language: php

php:
  - 5.4
  - 5.5
  - 5.6

script: ./vendor/bin/phpunit

cache:
  directories:
    - vendor

before_script:
  - composer install --optimize-autoloader --prefer-dist --no-interaction

env:
  - APP_ENV=unit_test

