debug: true

db.options:
  driver: pdo_mysql
  dbname: pony_express
  host: localhost
  user: pony_express
  password: pony_express_password
  charset: utf8

orm.em.options:
  mappings:
    -
      type: annotation
      namespace: PonyExpress
      path: 'src/Entities'
